"use client";

import { useEffect, useState } from "react";
import { useRoom } from "@/hooks/useRoom";
import { TokenPicker } from "@/components/multiplayer/TokenPicker";
import { RoomLobby } from "@/components/multiplayer/RoomLobby";
import { RollOffScreen } from "@/components/multiplayer/RollOffScreen";
import { GameLayoutMultiplayer } from "@/components/multiplayer/GameLayoutMultiplayer";
import { EntryShell } from "@/components/entry/EntryShell";
import { UiIcon } from "@/components/ui/UiIcon";
import type { PlayerToken } from "@/types/player";
import type { GameRules } from "@/types/game";

type Props = { initialCode?: string };
export function JoinRoom({ initialCode = "" }: Props) {
  const roomState = useRoom(); const { status, connected, connecting, room, myPlayerId, gameState, rollOff, error, joinRoom, startGame, rollForOrder, beginRollOffGame, leaveRoom, forfeitGame, clearError, sendAction, requestGameSync, tradeDraft, startTradeDraft, updateTradeDraft, cancelTradeDraft, submitTradeDraft } = roomState;
  const [name, setName] = useState(""); const [code, setCode] = useState(initialCode.toUpperCase()); const [token, setToken] = useState<PlayerToken | null>(null); const [tokenLabel, setTokenLabel] = useState(""); const [tokenColor, setTokenColor] = useState(""); const [formError, setFormError] = useState(""); const [previewTokens, setPreviewTokens] = useState<PlayerToken[]>([]); const [submitting, setSubmitting] = useState(false); const [sawPreGame, setSawPreGame] = useState(false);
  useEffect(() => { if (initialCode) setCode(initialCode.toUpperCase()); }, [initialCode]); useEffect(() => { if (error) setSubmitting(false); }, [error]);
  useEffect(() => { if (room?.status === "lobby" || room?.status === "rollOff") setSawPreGame(true); }, [room?.status]);
  useEffect(() => { const trimmed = code.trim().toUpperCase(); if (trimmed.length < 4) { setPreviewTokens([]); return; } const socketUrl = process.env.NEXT_PUBLIC_SOCKET_URL ?? "http://localhost:3001"; fetch(`${socketUrl}/room/${trimmed}`).then((r) => r.json()).then((data) => { if (data.ok && Array.isArray(data.takenTokens)) setPreviewTokens(data.takenTokens); }).catch(() => setPreviewTokens([])); }, [code]);
  function handleJoin() { const trimmedName = name.trim(); const trimmedCode = code.trim().toUpperCase(); if (!trimmedName) { setFormError("Enter your display name."); return; } if (!trimmedCode) { setFormError("Enter the room code."); return; } if (!token) { setFormError("Choose a token."); return; } if (submitting || !connected) return; setFormError(""); clearError(); setSubmitting(true); joinRoom({ displayName: trimmedName, roomCode: trimmedCode, token, tokenLabel, color: tokenColor }); }
  const takenTokens = room?.takenTokens ?? previewTokens;
  if (room && myPlayerId && room.status === "rollOff" && rollOff) return <RollOffScreen rollOff={rollOff} players={room.players} myPlayerId={myPlayerId} isHost={room.players.find((p) => p.playerId === myPlayerId)?.isHost ?? false} onRoll={rollForOrder} onBeginGame={beginRollOffGame} />;
  if (room && myPlayerId && gameState && room.status === "inGame") return <GameLayoutMultiplayer gameState={gameState} myPlayerId={myPlayerId} room={room} sendAction={sendAction} error={error} connectionStatus={status} onLeave={leaveRoom} onForfeit={forfeitGame} onRequestSync={requestGameSync} tradeDraft={tradeDraft} startTradeDraft={startTradeDraft} updateTradeDraft={updateTradeDraft} cancelTradeDraft={cancelTradeDraft} submitTradeDraft={submitTradeDraft} showStartSequence={sawPreGame} onStartSequenceShown={() => setSawPreGame(false)} />;
  if (room && myPlayerId) return <RoomLobby room={room} myPlayerId={myPlayerId} onStartGame={(rules: GameRules) => startGame(rules)} onLeave={leaveRoom} error={error} connectionStatus={status} />;
  return <EntryShell backHref="/"><section className="mx-auto max-w-2xl"><p className="wc-section-label text-[var(--wc-gold)]">Private departure</p><h1 className="wc-heading mt-2 text-white">Join Private Room</h1><p className="mt-2 text-slate-300">Enter your boarding code, select a token, and join the lounge.</p><form className="wc-panel mt-6 space-y-6" onSubmit={(event) => { event.preventDefault(); handleJoin(); }}><label className="grid gap-2 text-sm font-bold text-white" htmlFor="join-room-code">Room code<input id="join-room-code" value={code} onChange={(e) => { setCode(e.target.value.toUpperCase()); setFormError(""); }} maxLength={20} placeholder="e.g. LONDON-4821" className="wc-input wc-room-code text-lg uppercase" /></label><label className="grid gap-2 text-sm font-bold text-white" htmlFor="join-player-name">Player name<input id="join-player-name" value={name} onChange={(e) => { setName(e.target.value); setFormError(""); }} maxLength={30} placeholder="e.g. Bob" className="wc-input" /></label><TokenPicker selected={token} takenTokens={takenTokens} onChange={(nextToken, label, color) => { setToken(nextToken); setTokenLabel(label); setTokenColor(color); setFormError(""); }} />{(formError || error) && <p aria-live="polite" className="wc-validation wc-validation-danger">{formError || error}</p>}{connecting && <p className="wc-validation wc-validation-info">Connecting to multiplayer server…</p>}<button className="wc-button wc-button-primary w-full" type="submit" disabled={!connected || submitting}><UiIcon name="door" size={18} />{connected ? submitting ? "Joining room…" : "Join Room" : "Server unavailable"}</button></form></section></EntryShell>;
}
